# Generated by Django 4.2.13 on 2024-06-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0003_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
