# Generated by Django 4.2.13 on 2024-08-21 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0005_department_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab01.department'),
        ),
    ]
