# Generated by Django 4.2.13 on 2024-08-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0006_userinfo_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (2, '女')], null=True, verbose_name='性别'),
        ),
    ]
