# Generated by Django 4.2.13 on 2024-08-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0007_alter_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_num', models.CharField(max_length=20, verbose_name='项目编号')),
                ('proj_name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('proj_stat', models.SmallIntegerField(choices=[(1, '拟申请'), (2, '评审中'), (3, '已立项，研发中'), (4, '初步研发完成，小试中'), (5, '中试'), (6, '已转产')], verbose_name='项目状态')),
                ('apply_time', models.DateField(verbose_name='申请时间')),
                ('proof_time', models.DateField(verbose_name='立项时间')),
                ('rd_time', models.DateField(verbose_name='初研完成时间')),
                ('try_produ_time', models.DateField(verbose_name='中试时间')),
                ('production_time', models.DateField(verbose_name='转产时间')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab01.department', verbose_name='部门名称'),
        ),
        migrations.CreateModel(
            name='ExperimentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_num', models.CharField(max_length=20, verbose_name='单号')),
                ('record_time', models.DateField(verbose_name='实验日期')),
                ('expr_name', models.CharField(max_length=50, verbose_name='实验名称')),
                ('target', models.CharField(max_length=200, verbose_name='实验目的')),
                ('program', models.CharField(max_length=800, verbose_name='实验方案')),
                ('results', models.CharField(max_length=800, verbose_name='实验结果与分析')),
                ('conclusion', models.CharField(max_length=50, verbose_name='实验结论')),
                ('proj_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01.experimentproject', verbose_name='所属项目')),
            ],
        ),
    ]
