# Generated by Django 4.2.13 on 2024-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0009_alter_experimentproject_apply_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentproject',
            name='apply_time',
            field=models.DateField(default='-', verbose_name='调研开始时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='production_time',
            field=models.DateField(default='-', verbose_name='转产时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='proj_stat',
            field=models.SmallIntegerField(choices=[(1, '调研中'), (2, '评审中'), (3, '已立项，研发中'), (4, '初步研发完成，小试中'), (5, '中试'), (6, '已转产')], default=1, verbose_name='项目状态'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='proof_time',
            field=models.DateField(default='-', verbose_name='立项时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='rd_time',
            field=models.DateField(default='-', verbose_name='初研完成时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='try_produ_time',
            field=models.DateField(default='-', verbose_name='中试时间'),
        ),
    ]
