# Generated by Django 4.2.13 on 2024-08-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0011_alter_experimentproject_apply_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentproject',
            name='apply_time',
            field=models.DateField(blank=True, null=True, verbose_name='调研开始时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='production_time',
            field=models.DateField(blank=True, null=True, verbose_name='转产时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='proof_time',
            field=models.DateField(blank=True, null=True, verbose_name='立项时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='rd_time',
            field=models.DateField(blank=True, null=True, verbose_name='初研完成时间'),
        ),
        migrations.AlterField(
            model_name='experimentproject',
            name='try_produ_time',
            field=models.DateField(blank=True, null=True, verbose_name='中试时间'),
        ),
    ]
