# Generated by Django 4.2.13 on 2024-08-22 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0012_alter_experimentproject_apply_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentproject',
            name='apply_time',
            field=models.DateField(default=datetime.date(2024, 8, 22), verbose_name='调研开始时间'),
        ),
    ]
