# Generated by Django 4.2.13 on 2024-08-27 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0013_alter_experimentproject_apply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentproject',
            name='apply_time',
            field=models.DateField(default=datetime.date(2024, 8, 27), verbose_name='调研开始时间'),
        ),
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_num', models.CharField(max_length=20, verbose_name='订单号')),
                ('proj_name', models.CharField(max_length=32, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付')], default=1, verbose_name='状态')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab01.userinfo', verbose_name='用户ID')),
            ],
        ),
    ]
