# Generated by Django 4.2.13 on 2024-08-27 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab01', '0014_alter_experimentproject_apply_time_oder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentproject',
            name='apply_time',
            field=models.DateField(default=datetime.datetime(2024, 8, 27, 6, 7, 10, 942313, tzinfo=datetime.timezone.utc), verbose_name='调研开始时间'),
        ),
    ]
